### ISSUE TITLE
drawio generated svg diagram is not working in v1.18.0

### ISSUE THREAD

**Issue by wrliao** [andymchugh/andrewbmchugh-flow-panel#151]
flowpanel showed following error on svg diagram generated from draw.io. 

An unexpected error happened
Details
TypeError: crypto.randomUUID is not a function

    at http://host-ip:3000/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.18.0:26:41
    at r (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1:522)
    at v (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:12:152079)
    at s (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:12:152625)
    at div
    at section
    at L (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:32:26951)
    at div
    at div
    at q0 (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:17:169345)
    at Y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:15:140247)
    at i (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:197:3660)
    at Y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:15:140247)
    at div
    at http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:17:228732
    at http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:17:231409
    at M (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:225:4258)
    at R (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:211:9338)
    at C (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:217:5176)
    at div
    at R (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:217:14236)
    at div
    at div
    at sw (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:17:230363)
    at Y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:15:140247)
    at h (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:197:13447)
    at Y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:15:140247)
    at div
    at div
    at n (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:159:50659)
    at _t (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:170:67398)
    at div
    at I (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:159:101519)
    at Zt (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:170:72176)
    at Y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:15:140247)
    at LE (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:17:223449)
    at Cn (http://host-ip:3000/public/build/210.84523306629c3f2358df.js:1:2755)
    at Go (http://host-ip:3000/public/build/210.84523306629c3f2358df.js:3:87257)
    at Suspense
    at v (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:12:152079)
    at Pu (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:78790)
    at Du (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:79443)
    at T (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:4579)
    at kn (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:12248)
    at div
    at http://host-ip:3000/public/build/7836.7e2f7180984229d69bc9.js:1:155959
    at main
    at div
    at div
    at div
    at Ah (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:108906)
    at wh (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:113883)
    at zh (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:115041)
    at c (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:289:200891)
    at T (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:4579)
    at kn (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:12248)
    at Sn (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:11578)
    at st (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:234:18354)
    at x (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:5:197077)
    at Zt (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:243:41313)
    at Lc (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:115304)
    at div
    at g (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:294:68023)
    at y (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:147:9119)
    at p (http://host-ip:3000/public/build/78.e23f5de6c80448422166.js:377:139746)
    at C (http://host-ip:3000/public/build/4315.04038860e30ccfb6f1fb.js:176:36387)
    at c (http://host-ip:3000/public/build/7836.7e2f7180984229d69bc9.js:24:12175)
    at v (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:12:152079)
    at s (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:12:152625)
    at Ge (http://host-ip:3000/public/build/4315.04038860e30ccfb6f1fb.js:180:515)
    at Gh (http://host-ip:3000/public/build/8501.3217fca706c74baf8c8c.js:1561:117321)

grafana:/usr/share/grafana$ grafana-cli plugins ls | grep andrewbmchugh-flow-panel
andrewbmchugh-flow-panel @ 1.18.0

it's working well after downgrading to v1.17.0.

**Comment by andymchugh** [comment]
Thanks. It looks like the function is only available under https or localhost, not under http. I'll get that fixed.

**Comment by andymchugh** [comment]
Fixed in 1.18.1, just published. Thanks for spotting it.
